name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.26.x"

    - name: Build polaris-controller
      run: make build-amd64

    - name: Test
      run: go mod vendor && go test  -timeout 80m ./... -v -covermode=count -coverprofile=coverage_1.cover

    - name: Upload Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
